spring:
  profiles:
    active: dev


  datasource:
    driver-class-name: "org.mariadb.jdbc.Driver"
    url: jdbc:mariadb://localhost:3307/jwt?allowMultiQueries=true&useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&enabledTLSProtocols=TLSv1.2&verifyServerCertificate=false&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  redis:
    port: 6379
    host: localhost
    password:

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

jwt:
  secret: '123456789012345678901234567890123456789012345678901234567890'

app:
  auth:
    tokenSecret: '1234'
    tokenExpiry: 1800000 # 30min
    refreshTokenExpiry: 3600000 # 30min

logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: debug
